---
- name: Are there local IPv4 networks?
  tags: firewall
  set_fact:
    localNetwork4: True
  loop: "{{ networks }}"
  when: item.network4 is defined and item.network4 != ""

- name: Are there local IPv6 networks?
  tags: firewall
  set_fact:
    localNetwork6: True
  loop: "{{ networks }}"
  when: item.network6 is defined and item.network6 != ""

- name: debug
  debug:
    msg: Foo "{{ localNetwork6 }}"

- name: Set IPv4 forward to 1
  tags: firewall
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  when: localNetwork4

- name: Set IPv6 forward to 1
  tags: firewall
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  when: localNetwork6

- name: Install nftables package
  tags: firewall
  apt:
    name: "{{ packages }}"
  vars:
   packages:
     - nftables

- name: Create nftables config directory
  tags: firewall
  file:
    dest: /etc/nftables.conf.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Basic firewall config files
  tags: firewall
  set_fact:
    firewallConfig:
     - nftables.conf
     - nftables.conf.d/10rfcDef.nft
     - nftables.conf.d/20siteDef.nft
     - nftables.conf.d/30localDef.nft
     - nftables.conf.d/50rules.nft
    firewallNATConfig:
     - nftables.conf.d/40nat.nft

- name: Is NAT required?
  tags: firewall
  set_fact:
    firewallNAT: True
  when: item.nat is defined and item.nat != []
  with_items:
   - "{{ networks }}"

- name: Add NAT to firewall config
  tags: firewall
  set_fact:
    firewallConfig: "{{ firewallConfig + firewallNATConfig }}"
  when: firewallNAT

- name: Deploy nftables firewall rules
  tags: firewall
  template:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  notify: restart nftables
  with_items:
   - "{{ firewallConfig }}"

- name: Enable nftables
  tags: firewall
  systemd:
    name: nftables
    enabled: yes

